package frc.robot.subsystems.led;

public class LEDConstants {
  public static final int port = 0;
  public static final int LEDLength = 120;

  public enum BlinkinValues {
    /*
    * Fixed Palette Pattern
    */
    RAINBOW_RAINBOW_PALETTE(0),
    RAINBOW_PARTY_PALETTE(1),
    RAINBOW_OCEAN_PALETTE(2),
    RAINBOW_LAVA_PALETTE(3),
    RAINBOW_FOREST_PALETTE(4),
    RAINBOW_WITH_GLITTER(5),
    CONFETTI(6),
    SHOT_RED(7),
    SHOT_BLUE(8),
    SHOT_WHITE(9),
    SINELON_RAINBOW_PALETTE(10),
    SINELON_PARTY_PALETTE(11),
    SINELON_OCEAN_PALETTE(12),
    SINELON_LAVA_PALETTE(13),
    SINELON_FOREST_PALETTE(14),
    BEATS_PER_MINUTE_RAINBOW_PALETTE(15),
    BEATS_PER_MINUTE_PARTY_PALETTE(16),
    BEATS_PER_MINUTE_OCEAN_PALETTE(17),
    BEATS_PER_MINUTE_LAVA_PALETTE(18),
    BEATS_PER_MINUTE_FOREST_PALETTE(19),
    FIRE_MEDIUM(20),
    FIRE_LARGE(21),
    TWINKLES_RAINBOW_PALETTE(22),
    TWINKLES_PARTY_PALETTE(23),
    TWINKLES_OCEAN_PALETTE(24),
    TWINKLES_LAVA_PALETTE(25),
    TWINKLES_FOREST_PALETTE(26),
    COLOR_WAVES_RAINBOW_PALETTE(27),
    COLOR_WAVES_PARTY_PALETTE(28),
    COLOR_WAVES_OCEAN_PALETTE(29),
    COLOR_WAVES_LAVA_PALETTE(30),
    COLOR_WAVES_FOREST_PALETTE(31),
    LARSON_SCANNER_RED(32),
    LARSON_SCANNER_GRAY(33),
    LIGHT_CHASE_RED(34),
    LIGHT_CHASE_BLUE(35),
    LIGHT_CHASE_GRAY(36),
    HEARTBEAT_RED(37),
    HEARTBEAT_BLUE(38),
    HEARTBEAT_WHITE(39),
    HEARTBEAT_GRAY(40),
    BREATH_RED(41),
    BREATH_BLUE(42),
    BREATH_GRAY(43),
    STROBE_RED(44),
    STROBE_BLUE(45),
    STROBE_GOLD(46),
    STROBE_WHITE(47),

    /*
    * CP1: Color 1 Pattern
    */
    CP1_END_TO_END_BLEND_TO_BLACK(48),
    CP1_LARSON_SCANNER(49),
    CP1_LIGHT_CHASE(50),
    CP1_HEARTBEAT_SLOW(51),
    CP1_HEARTBEAT_MEDIUM(52),
    CP1_HEARTBEAT_FAST(53),
    CP1_BREATH_SLOW(54),
    CP1_BREATH_FAST(55),
    CP1_SHOT(56),
    CP1_STROBE(57),

    /*
    * CP2: Color 2 Pattern
    */
    CP2_END_TO_END_BLEND_TO_BLACK(58),
    CP2_LARSON_SCANNER(59),
    CP2_LIGHT_CHASE(60),
    CP2_HEARTBEAT_SLOW(61),
    CP2_HEARTBEAT_MEDIUM(62),
    CP2_HEARTBEAT_FAST(63),
    CP2_BREATH_SLOW(64),
    CP2_BREATH_FAST(65),
    CP2_SHOT(66),
    CP2_STROBE(67),

    /*
    * CP1_2: Color 1 and 2 Pattern
    */
    CP1_2_SPARKLE_1_ON_2(68),
    CP1_2_SPARKLE_2_ON_1(69),
    CP1_2_COLOR_GRADIENT(70),
    CP1_2_BEATS_PER_MINUTE(71),
    CP1_2_END_TO_END_BLEND_1_TO_2(72),
    CP1_2_END_TO_END_BLEND(73),
    CP1_2_NO_BLENDING(74),
    CP1_2_TWINKLES(75),
    CP1_2_COLOR_WAVES(76),
    CP1_2_SINELON(77),

    /*
    * Solid color
    */
    HOT_PINK(78),
    DARK_RED(79),
    RED(80),
    RED_ORANGE(81),
    ORANGE(82),
    GOLD(83),
    YELLOW(84),
    LAWN_GREEN(85),
    LIME(86),
    DARK_GREEN(87),
    GREEN(88),
    BLUE_GREEN(89),
    AQUA(90),
    SKY_BLUE(91),
    DARK_BLUE(92),
    BLUE(93),
    BLUE_VIOLET(94),
    VIOLET(95),
    WHITE(96),
    GRAY(97),
    DARK_GRAY(98),
    BLACK(99);

    public final int value;

    private BlinkinValues(int value) {
      this.value = value;
    }
  };
}